version: 2

# Run the welcome/run job in its own container
jobs:
  build:
    docker:
      - image: sptkl/docker-geosupport:19b2
      - image: docker:19.03.1

    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: pip install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: run unittest
          command: |
            python -m unittest
      - run: 
          name: Build and publish docker image
          command: |
            TAG="${CIRCLE_SHA1}"
            docker build -t sptkl/api-geosupport:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push sptkl/api-geosupport:$TAG
            docker tag sptkl/api-geosupport:$TAG sptkl/api-geosupport:latest
            docker push sptkl/api-geosupport:latest
      - run:
          name: Avoid hosts unknown for github
          command: ssh-keyscan geosupport-api.planninglabs.nyc >> ~/.ssh/known_hosts
      - deploy:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git remote add dokku dokku@geosupport-api.planninglabs.nyc:geosupport-api && git push dokku master
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              git remote add dokku dokku@geosupport-api.planninglabs.nyc:geosupport-api-staging && git push dokku develop:master
            fi